### ISSUE TITLE
MBOX file requires extension for ratom to run properly

### ISSUE THREAD

**Issue by laissezfarrell** [libratom/libratom#141]
running `ratom report -mvvp` on an MBOX file without an extension, results in an empty SQLITE3 db file (with the stdout progress bar reading that no messages were discovered). After appending .mbox to the filename, the report function works as expected.

**Comment by adetorcy** [comment]
Thanks for the feedback. This is expected behavior, with the current code. The CLI tool looks at the file extension to determine what type of mail archive a file is ([here](https://github.com/libratom/libratom/blob/0.4.3/libratom/lib/core.py#L34-L43)). If this is an issue we can probably make the code smarter.

**Comment by laissezfarrell** [comment]
That makes sense. If it is in the user documentation, I missed it (sorry if it is!). If not, adding it in the user docs would be good. We had a donor transfer an mbox that did not have the extension, which is easy enough to append.
