### ISSUE TITLE
Ability to override/ignore sub-dependencies

### ISSUE THREAD

**Issue by rkbeatss** [libratom/libratom#163]
**Problem**

I generally just want to use the PST related functionalities in the lib, mainly in `pff.py.` Therefore, `sqlalchemy==1.4.8` or `numpy==1.20.2 `are not needed for my use case. How can I ignore these dependencies in a robust way?

**Suggestions**

-  make dependency range more lenient 
- separate requirements files (`optional-requirements.txt`,` mandatory-requirements.txt`)
- support extras, so we can get the relevant dependencies through `pip install libratom[database]`

Suggestions/tips for me are more than welcome, thank you ☺️

**Comment by adetorcy** [comment]
Other than being unnecessary, what is your incentive for skipping those dependencies?

You can make your own requirement file if you have to. I would recommend starting from the requirements.txt file that comes with the version of libratom you are installing, and editing that file to remove the dependencies you want to skip. That could look like this:

- Install libratom without its dependencies: `pip install --no-deps libratom`
- Install the packages in your requirements file: `pip install --no-warn-conflicts -r ./my_edited_requirements.txt`

**Comment by jendrikjoe** [comment]
I know this is closed and very old, but as we ran into the same issue I wanted to give some extra motivation on why relaxing the dependency constraint would be helpful 🤗 
We (and a lot of other people) are using poetry for managing dependencies, when installing dependencies. The same argument applies to tools like pip and piping too though. If you add a package it goes through all its dependencies and the ones of all other packages and tries to find a set of versions that work. The issue we ran into specifically is if you try to install libratom alongside the newest version of black.
A minimum reproducible pyproject.toml file would be

```
[tool.poetry]
name = "test-package"
version = "0.1.0"
description = "A package to test libratom conflicts"

license = "Apache"

authors = [
    "Foo Bar <foo.bar@test.com>"
]

readme = 'README.md'  # Markdown files are supported

repository = "https://github.com/libratom/libratom"
homepage = "https://github.com/libratom/libratom"

[tool.poetry.dependencies]
python = "^3.11"
libratom = "^0.7.1"


[tool.poetry.group.dev.dependencies]
black = "^24"
```

If you try to resolve dependencies one will get the error

```
    And because black (24.3.0) depends on packaging (>=22.0)
 and black (24.4.0) depends on packaging (>=22.0), black (>=24.0,<24.4.1 || >24.4.1,<24.4.2 || >24.4.2) requires packaging (>=22.0).
    And because black (24.4.1) depends on packaging (>=22.0)
 and black (24.4.2) depends on packaging (>=22.0), black (>=24.0) requires packaging (>=22.0).
(1) So, because libratom (0.7.1) depends on packaging (21.3)
 and no versions of libratom match >0.7.1,<0.8.0, black (>=24.0) is incompatible with libratom (>=0.7.1,<0.8.0).
```

As I assume you don't rely on the specific version of `packaging==21.3` but `packaging>=21` would probably be fine for you it would lower the burden on people installing your library in larger projects a lot easier 🙂 
Installing it with --no-deps is as well not an option when using libraries in other projects, because it would force people to go through every single installed library check its dependencies and install them manually that is what dependency resolvers are there for to automate and pinning dependencies more strictly that necessary breaks that pattern 🤗 

We went for removing it from the resolver for now and installing it and all its dependencies manually, but I thought the comment could still be helpful to increase adoption of your library 🤗
